name: Build & Deploy FastAPI App
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sawandevrani/fastapi
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t $IMAGE_NAME:latest -f Dockerfile .
        docker push $IMAGE_NAME:latest

    - name: Update image in K8s manifest
      run: |
        sed -i "s|image: .*|image: $IMAGE_NAME:latest|" k8s/fastapi-deployment.yaml


    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: sawandevrani
        author_email: sawandevrani28@gmail.com
        message: "Update image to latest"
        add: "k8s/fastapi-deployment.yaml"
        github_token: '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'
#